### ISSUE TITLE
Names of columns in relationships should be the same

### ISSUE THREAD

**Issue by marcosqlbi** [TabularEditor/BestPracticeRules#1]
The names of the columns involved in a relationships should be the same, unless there are more relationships to the same table (e.g. Order Date, Start Date).

**Comment by otykier** [comment]
The following expression lists relationships where:

- The relationship is the only existing relationship between two tables, and the FromColumn and ToColumn are not identically named

**or**

- The relationship is one of multiple relationships between the same two tables, but where the FromColumn name does not end with the ToColumn name. E.g. if the dimension key is called **DateKey**, surrogate keys needs to be named Order**DateKey**, Due**DateKey**, Ship**DateKey**, etc...

```
(
    Model.Relationships.Count(FromTable = OuterIt.FromTable and ToTable = OuterIt.ToTable) = 1 and 
    FromColumn.Name <> ToColumn.Name
)
or
(
    Model.Relationships.Count(FromTable = OuterIt.FromTable and ToTable = OuterIt.ToTable) > 1 and
    not FromColumn.Name.EndsWith(ToColumn.Name)
)
```

[Rule definition](https://github.com/TabularEditor/BestPracticeRules/blob/master/src/standard/Naming/RELATIONSHIP_COLUMN_NAMES.json)
