### ISSUE TITLE
[Rule Submit] LAYOUT: Hide Fact, Bridge or User tables

### ISSUE THREAD

**Issue by Gezahegne** [TabularEditor/BestPracticeRules#10]
"ID": "LAYOUT:_HIDE_FACT,_BRIDGE_OR_USER_TABLES",
    "Name": "LAYOUT: Hide Fact, Bridge or User tables",
    "Category": null,
    "Description": "Fact, Bridge or User tables should be hidden. Right click the table name and select 'Hide from Client Tools'",
    "Severity": 3,
    "Scope": "Table",
    "ScopeString": "Tables",
    "Expression": "(Name.ToLower().Contains(\"bridge\") or Name.ToLower().Contains(\"fact\") or Name.ToLower().Contains(\"user\"))\nand not IsHidden\n",
    "FixExpression": null,
    "Compatibility": null,
    "IsValid": false

**Comment by otykier** [comment]
Won't add to standard repository, as this relies on organization-specific naming convention.
