### ISSUE TITLE
[Rule Submit] LAYOUT: Format Measures in one of the set of predefined formats for the cube

### ISSUE THREAD

**Issue by Gezahegne** [TabularEditor/BestPracticeRules#11]
"ID": "LAYOUT:_FORMAT_MEASURES_IN_ONE_OF_THE_SET_OF_PREDEFINED_FORMATS_FOR_THE_CUBE
",
    "Name": "LAYOUT: Format Measures in one of the set of predefined formats for the cube",
    "Category": null,
    "Description": "Measure formatting should be one of these: currency no decimals, percentage with comma & 1 or 2 decimals, whole number with comma & no decimals, decimal with comma & 1 decimal.",
    "Severity": 10,
    "Scope": "Measure",
    "ScopeString": "Measures",
    "Expression": "(!FormatString.Equals(\"\\$#,0;(\\$#,0);\\$#,0\") \nand !FormatString.Equals(\"#,0.0 %;-#,0.0 %;#,0.0 %\")\nand !FormatString.Equals(\"#,0.00 %;-#,0.00 %;#,0.00 %\")\nand !FormatString.Equals(\"0.0 %;-0.0 %;0.0 %\")\nand !FormatString.Equals(\"0.00 %;-0.00 %;0.00 %\")\nand !FormatString.Equals(\"\\$#,0.0;(\\$#,0.0);\\$#,0.0\")\nand !FormatString.Equals(\"#,0.0\")\nand !FormatString.Equals(\"0.0\")\nand !FormatString.Equals(\"0\")\nand !FormatString.Equals(\"#,0\")) and not IsHidden",
    "FixExpression": null,
    "Compatibility": null,
    "IsValid": false

**Comment by otykier** [comment]
Won't add to standard repository, as this relies on organization-specific conventions for format strings.
