### ISSUE TITLE
[Rule Submit] META: Database connection must be with specific 'DatabaseName' & specific servers only

### ISSUE THREAD

**Issue by Gezahegne** [TabularEditor/BestPracticeRules#12]
"ID": "DATABASE_CONNECTION_MUST_BE_WITH_SPECIFIC_'DATABASENAME'_&_SERVERS_IN('SERVER1','SERVER2','SERVER3','SERVER4','SERVER3,60793')",
    "Name": "META: Database connection must be with specific 'DatabaseName' & specific servers only",
    "Category": null,
    "Description": "All the cube data comes from a single database named source, DatabaseName, in these servers (Server1, Server3, Server3,60793, Server2, Server4, abivmscentral66). If you have data coming other than from these list of servers and database name, please check and get from these list of servers and database only. If you can't get the data in these servers/database contact the database team.",
    "Severity": 10,
    "Scope": "DataSource",
    "ScopeString": "Data Sources",
    "Expression": "!Name.ToLower().Equals(\"sqlserver Server1 DatabaseName\")\nand !Name.ToLower().Equals(\"sqlserver Server3 DatabaseName\")\nand !Name.ToLower().Equals(\"sqlserver Server3,60793 DatabaseName\")\nand !Name.ToLower().Equals(\"sqlserver Server2 DatabaseName\")\nand !Name.ToLower().Equals(\"sqlserver Server4 DatabaseName\")\nand !Name.ToLower().Equals(\"sqlserver abivmscentral66 DatabaseName\")",
    "FixExpression": null,
    "Compatibility": null,
    "IsValid": false

**Comment by otykier** [comment]
Won't add to standard repository, as this relies on organization-specific naming convention.
