### ISSUE TITLE
[Rule Submit] Visible Measure need to have formatting

### ISSUE THREAD

**Issue by Gezahegne** [TabularEditor/BestPracticeRules#13]
"ID": "META:_VISIBLE_MEASURE_NEED_TO_HAVE_FORMATTING",
    "Name": "META: Visible Measure need to have formatting",
    "Category": null,
    "Description": "Visible Measure need to have specific formatting and should not default to General",
    "Severity": 3,
    "Scope": "Measure",
    "ScopeString": "Measures",
    "Expression": "(String.IsNullOrWhiteSpace(FormatString)) and not IsHidden",
    "FixExpression": null,
    "Compatibility": null,
    "IsValid": false

**Comment by otykier** [comment]
Added to standard repository, thanks for submitting.
