### ISSUE TITLE
[Rule Submit] META: Foreign and Primary Keys should be INT

### ISSUE THREAD

**Issue by Gezahegne** [TabularEditor/BestPracticeRules#16]
"ID": "META:_FOREIGN_AND_PRIMARY_KEYS_SHOULD_BE_INT",
    "Name": "META: Foreign and Primary Keys should be INT",
    "Category": null,
    "Description": "Foreign and Primary Keys should be INT data type. ",
    "Severity": 3,
    "Scope": "DataColumn, CalculatedColumn, CalculatedTableColumn",
    "ScopeString": "Columns",
    "Expression": "(Name.ToLower().EndsWith(\"id\") or Name.ToLower().EndsWith(\"key\"))\nand !DataType.ToString().Equals(\"Int64\")",
    "FixExpression": null,
    "Compatibility": null,
    "IsValid": false

**Comment by otykier** [comment]
This is a matter of data modelling for Tabular. There may be good reasons to have other data types for FK / PK columns than Int64, and as such, this rule will not be added as a standard rule.
