### ISSUE TITLE
[Rule Submit] META: Attributes that are visible and Int64 should be set to do not summarize

### ISSUE THREAD

**Issue by Gezahegne** [TabularEditor/BestPracticeRules#18]
"ID": "META:_COLUMNS_THAT_ARE_VISIBLE_AND_INT64_SHOULD_BE_SET_TO_DO_NOT_SUMMARIZE",
    "Name": "META: Attributes that are visible and Int64 should be set to do not summarize",
    "Category": null,
    "Description": "Attributes that are vissible and their data type is Int 64 need to be set to DO NOT SUMMARIZE. DO NOT SUMMARIZE is one of the 'Reporting Properties' in Visual Studio ('Other' in Tabular Editor) and is found under 'Summarize By'.",
    "Severity": 3,
    "Scope": "DataColumn, CalculatedColumn, CalculatedTableColumn",
    "ScopeString": "Columns",
    "Expression": "DataType.ToString().Equals(\"Int64\") and !SummarizeBy.ToString().Equals(\"None\") and not IsHidden",
    "FixExpression": null,
    "Compatibility": null,
    "IsValid": false

**Comment by otykier** [comment]
[Rule implemented](https://github.com/TabularEditor/BestPracticeRules/blob/master/src/standard/Metadata/META_SUMMARIZE_NONE.json)

All visible columns of type Int64, Decimal or Double will be reported. Columns on hidden tables are not reported.
