### ISSUE TITLE
"Remove unused columns" rule error

### ISSUE THREAD

**Issue by daniilmaslyuk** [TabularEditor/BestPracticeRules#19]
The "Remove unused columns" rule returns the following error:
`No property or field 'Dependants' exists in type 'DataColumn'`

![image](https://user-images.githubusercontent.com/10683126/38600825-e500db14-3da8-11e8-9720-953613d6d0a2.png)
I tried this on both 1200 and 1400 compatibility levels, and I still get the same error.

Other rules do not have such issues.

Am I doing something incorrectly?

**Comment by otykier** [comment]
Thanks for reporting this. There was a breaking change in the underlying data model of Tabular Editor 2.7, in which I forgot to update the definition of this rule. Could you please try to change the expression of the rule to:

```
(IsHidden or Table.IsHidden)
and ReferencedBy.Count = 0 
and (not UsedInRelationships.Any())
and (not UsedInSortBy.Any())
and (not UsedInHierarchies.Any())
and (not Table.RowLevelSecurity.Any(
    it <> null and 
    it.IndexOf("[" + current.Name + "]", "OrdinalIgnoreCase") >= 0
))
and (not Model.Roles.Any(RowLevelSecurity.Any(
    it <> null and 
    (
        it.IndexOf(current.Table.Name + "[" + current.Name + "]", "OrdinalIgnoreCase") >= 0 or
        it.IndexOf("'" + current.Table.Name + "'[" + current.Name + "]", "OrdinalIgnoreCase") >= 0
    )
)))
```

Not only does this support the new data model in 2.7, but it also does some additional checks to make sure that a column isn't being used in RLS.

I've updated the [source for this rule](https://github.com/TabularEditor/BestPracticeRules/blob/master/src/standard/Performance/PERF_UNUSED_COLUMNS.json), and by the way, I've also added a [PERF_UNUSED_MEASURES](https://github.com/TabularEditor/BestPracticeRules/blob/master/src/standard/Performance/PERF_UNUSED_MEASURES.json) rule. Let me know if you have any further issues!
