### ISSUE TITLE
Do not use floating point data types

### ISSUE THREAD

**Issue by DaniilMaslyuk** [TabularEditor/BestPracticeRules#21]
I think this rule should not be applied to measures, because there is no way of changing the data type of measures by changing the metadata, as far as I'm aware.

In fact, if you try to apply a fix, you will get the following error:
![image](https://user-images.githubusercontent.com/10683126/38786722-0dabe97e-416d-11e8-9a91-b1b76a639a49.png)

Also, for clarity purposes, I would change the description from:
> Floating point datatypes can cause unexpected results when evaluating values close to 0. Use Decimal instead.

To something like this:
> Floating point datatypes can cause unexpected results when evaluating values close to 0. Use **Currency / Fixed Decimal Number (decimal)** instead.

Because in Visual Studio, the floating point data type is called Decimal Number, which could be confusing when people are instructed to "use Decimal instead".

**Comment by otykier** [comment]
Agreed - updated the rule.
