### ISSUE TITLE
Don't summarize numeric columns

### ISSUE THREAD

**Issue by DaniilMaslyuk** [TabularEditor/BestPracticeRules#22]
I think this rule should be restricted to only work on numeric columns, as the rule name implies.

Also, hidden tables should be excluded. There is already a condition to exclude hidden columns, but this is not sufficient, because columns in hidden tables are marked as visible unless explicitly hidden (which is redundant).

I think this issue can be solved by using the following rule expression:
```
IsHidden = false

and Table.IsHidden = false

and SummarizeBy <> "None"

and (DataType = "Double" or DataType = "Decimal" or DataType = "Int64")
```

**Comment by otykier** [comment]
Thanks again. Rule updated.
