### ISSUE TITLE
[Rule Request] Sort By Column

### ISSUE THREAD

**Issue by DomAtGitHub** [TabularEditor/BestPracticeRules#23]
Hi Daniel,

I want to check if a column is sorted by another column. What expression would do it?
I've tried "IsHidden = false and sortByColumn <> null" but it did not work. Can you help me out here, please?

Thanks in advance.
Dominik

**Comment by NielsSkytte** [comment]
Same question here :-) I've tried setting the IsAvailableInMDX property to false for an entire model, but all fields that are sorted by another column get an error with ''column xxxxx' does not have an attribute hierarchy enabled.' 

So an easy option would be let those columns that are sorted by to 'true' for IsAvailableInMDX ...or perhaps there is a better option? Anyways, need the same answer :-)

regards Niels

**Comment by otykier** [comment]
@DomAtGitHub What error message did you get? The following BPA expression should work fine:
`IsHidden = false and SortByColumn <> null`
Make sure that only "Calculated Columns", "Calculated Table Columns" and "Data Columns" is selected in the "Applies to" dropdown:

![image](https://user-images.githubusercontent.com/8976200/44728647-ded0b600-aa91-11e8-8f9d-678fc4f42744.png)

@NielsSkytte You can use the following expression to find columns that are used as the Sort By-property of other columns:

`UsedInSortBy.Any()`

Let me know if you have any further questions!

**Comment by NielsSkytte** [comment]
Worked fine, will create a separate thread for 'turning off'  IsAvailableInMDX for an entire model, few more things need to be done.

**Comment by DomAtGitHub** [comment]
@otykier Indeed, you are right. It works. In my case I added “model” on accident to the rule, which of course is not correct. Thanks for your help. Issue solved. ;)
