### ISSUE TITLE
[Rule Request] Copy Expression into Description when empty

### ISSUE THREAD

**Issue by kemnyc** [TabularEditor/BestPracticeRules#25]
This rule would check for null descriptions and for those found copy the Expression into the Description.
For deployed models, this would be a starting point to give visibility to users of what calculations are being made in the measure, calculated column, or calculated table.

**Comment by otykier** [comment]
Great suggestion!

The following JSON should do the trick (copy it into your %appdata%\..\Local\TabularEditor\BPARules.json file):

```json
  {
    "ID": "AVOID_EMPTY_DESCRIPTIONS",
    "Name": "Avoid empty descriptions",
    "Category": "Metadata",
    "Description": "Provide a description for all calculated objects.",
    "Severity": 1,
    "Scope": "Measure, CalculatedColumn, CalculatedTable",
    "Expression": "string.IsNullOrWhitespace(Description)",
    "CompatibilityLevel": 1200
  }
```

Unfortunately, the BPA framework does not currently allow setting the Description property of an object, based on another property. Also - you'd want a way to maintain the descriptions, in case you change an expression later on or provide a custom description. Use the following script for that (I suggest saving it as a Custom Action at the Model-level):

```csharp
// Construct a list of all measures, calculated columns and calculated tables:
var objects = new List<dynamic>();
objects.AddRange(Model.AllMeasures);
objects.AddRange(Model.AllColumns.OfType<CalculatedColumn>());
objects.AddRange(Model.Tables.OfType<CalculatedTable>());

// Loop through all objects:
foreach(var obj in objects)
{
    // If a description is empty, or the "ExpressionAsDescription" annotation was previously set to "1"...
    if(string.IsNullOrWhiteSpace(obj.Description) || obj.GetAnnotation("ExpressionAsDescription")=="1")
    {
        // Update the description from the expression:
        obj.Description = obj.Expression;

        // Set the "ExpressionAsDescription" annotation to 1:
        obj.SetAnnotation("ExpressionAsDescription", "1");
    }
}
```

The script sets an annotation on every object where the description was updated. This annotation is then used going forward, to make sure descriptions are still updated the next time you run the script. If at some point, you supply a custom description of an object, make sure to remove the annotation (or set it to a value different than "1"), to make sure the script won't override the custom description provided.

Let me know if you have any questions!

**Comment by kemnyc** [comment]
Hello Daniel,

Thank you so much for this code! I tried the script (figured out where to use it) and it works beautifully to populate the Description with the Expression. It will save us much time in documenting our models so there’s visibility on the DAX measures. And I understand how the Annotations work. So now I have another question. How do I write the code to insert the current date as well to the annotations?  This code added to the script you provided works:

// Set the "DescriptionLastUpdate" annotation to current date:
        obj.SetAnnotation("DescriptionLastUpdate", "2019-02-14");

However, what is the code to determine the date automatically based on the system date?

Thank you so much for your help!

Best,
Karen

**Comment by otykier** [comment]
Hi Karen,
Sorry for not responding sooner - I lost notifications for this repository. You've probably already moved on, but just in case others find this thread, you can get the current system date in C# like so.

```csharp
obj.SetAnotation("DescriptionLastUpdate", DateTime.Now.ToString("yyyy-MM-dd"));
```
