### ISSUE TITLE
[Rule Request] For SQL connection strings Provider MSOLEDBSQL should be used

### ISSUE THREAD

**Issue by sqlenders** [TabularEditor/BestPracticeRules#27]
Connection strings should not contain SQLOLEDB or SQLNCLI. It should be changed to MSSQLOLEDB. Source : https://docs.microsoft.com/en-us/sql/connect/oledb/oledb-driver-for-sql-server?view=sql-server-2017

**Comment by otykier** [comment]
In my experience, SQLNCLI can be faster than both SQLOLEDB and MSSQLOLEDB, so that's the one I normally use. Care to elaborate why you'd prefer MSSQLOLEDB?

**Comment by sqlenders** [comment]
From the Microsoft site : 
The new OLE DB provider is called the Microsoft OLE DB Driver for SQL Server (MSOLEDBSQL). The new provider will be updated with the most recent server features going forward.

Some features are :
- snapshot isolation you can use to read from a OLTP database without locking anything.
- Azure Active Directory is improved. 
- you can specify ApplicationIntent=ReadOnly which will redirect you a secondary server

**Comment by otykier** [comment]
Thanks for suggesting this. This rule has now been added to the standard repository.
