### ISSUE TITLE
Names of visible objects must start with uppercase letter

### ISSUE THREAD

**Issue by marcosqlbi** [TabularEditor/BestPracticeRules#3]
Avoid using prefixes and camelCasing. Use "Sales" instead of "dimSales" or "mSales".

**Comment by otykier** [comment]
Similar to #2 this rule is divided into two: One for columns and hierachies, another for measures and tables. The expression is quite simple:

```
not (IsHidden or Table.IsHidden)
and char.IsLower(Name[0])
and (Model.Cultures.Count = 0 or TranslatedNames.Any(it = "" or it = outerIt.Name))
```

- Object is visible and parent table is visible **AND**
- First character of the name is lowercase **AND**
- A translated name different from the object name has not been supplied (in case the model uses translations)

[Rule definition for columns and hierarchies](https://github.com/TabularEditor/BestPracticeRules/blob/master/src/standard/Naming/UPPERCASE_FIRST_LETTER_COLUMNS_HIERARCHIES.json)
[Rule definition for measures and tables](https://github.com/TabularEditor/BestPracticeRules/blob/master/src/standard/Naming/UPPERCASE_FIRST_LETTER_MEASURES_TABLES.json)
