### ISSUE TITLE
[Rule Submit] Disable Avaliable In MDX for Hidden Columns

### ISSUE THREAD

**Issue by mlonsk** [TabularEditor/BestPracticeRules#30]
Hi

Hidden columns should have Avaliable In MDX disabled to optimize processing time
  {
    "ID": "DISABLE_ATTRIBUTE_HIERACHIES",
    "Name": "Disable attribute hierachies to decrease processing",
    "Category": "Metadata",
    "Description": "Disable Attribute hierarchies for hidden collumns. This will ensure faster processing.",
    "Severity": 2,
    "Scope": "DataColumn",
    "Expression": " IsHidden \n\nand (IsAvailableInMDX == TRUE)\n\nand (not UsedInHierarchies.Any())",
    "FixExpression": "IsAvailableInMDX = false"
  }

**Comment by otykier** [comment]
Added to repository. Thanks for submitting!
