### ISSUE TITLE
Translate display folders rule reports incorrect violations

### ISSUE THREAD

**Issue by didierterrien** [TabularEditor/BestPracticeRules#32]
Hi Daniel,
I'm impressed by your presentation of Tabular Editor. It's definitely a key tool in Power BI environment. Congratulation again !
As you know, I work on automatic translations and I got already some good results. So I was very interrested in the rule about "Translate display folders" but I think there is a bug there. As you can see on the screenshot, the rule reports some translations are missing but in the column or measure the properties reports "0 empty".
Additionaly, after I added the standard rules as you demonstrated in the video, opening the bim file takes now  a lot of time. The bim file is attached

Thanks in advance

[PBI translations.zip](https://github.com/TabularEditor/BestPracticeRules/files/4445010/PBI.translations.zip)

![Image 1](https://user-images.githubusercontent.com/37301981/78679407-74792c00-78ea-11ea-90a7-5b3e1a1d931d.png)

**Comment by otykier** [comment]
Thanks for reporting. This has been fixed now: https://raw.githubusercontent.com/TabularEditor/BestPracticeRules/master/BPARules-standard.json
