### ISSUE TITLE
Define format string for visible measures

### ISSUE THREAD

**Issue by marcosqlbi** [TabularEditor/BestPracticeRules#4]
Every visible measure should have format string. Automatic number of decimals is a warning, because it is likely to be wrong.

**Comment by otykier** [comment]
This rule is quite simple:

```
not IsHidden 
and string.IsNullOrWhitespace(FormatString)
```

[Rule definition](https://github.com/TabularEditor/BestPracticeRules/blob/master/src/standard/Formatting/APPLY_FORMAT_STRING_MEASURES.json)
