### ISSUE TITLE
camelCase rule is causing false positives on PascalCasing

### ISSUE THREAD

**Issue by alxdean** [TabularEditor/BestPracticeRules#54]
The Rule "Avoid CamelCase on visible measures and tables" (BPA-Standard) is checking for the first letter being upper case. That would be PascalCasing and not camelCasing. in camelCasing the first letter is lower case.

**Comment by otykier** [comment]
You're right. The name of the rule should be "Avoid PascalCase on visible measures and tables".

**Comment by alxdean** [comment]
We'll, that woukd be the correct name for the regex, but I don't agree. I
find PascalCase a better standard for visible tables and measures :-)

If fixing anything, then the Regex should be fixed to match the rule :-)

**Comment by otykier** [comment]
The rules are mostly inspired by [this article](https://www.sqlbi.com/articles/data-import-best-practices-in-power-bi/). The good news is, however, that you are free to customize and change them anyway you see fit :)
