### ISSUE TITLE
[Rule Request] Provide short rule description

### ISSUE THREAD

**Issue by panserbjoern** [TabularEditor/BestPracticeRules#55]
I would like all rules to have category name in the beginning as per Microsofts own analysis-service\bpa directory.

Right now I am joining 
https://raw.githubusercontent.com/TabularEditor/BestPracticeRules/master/BPARules-standard.json"
with
https://raw.githubusercontent.com/microsoft/Analysis-Services/master/BestPracticeRules/BPARules.json

But TabularEditors BPA collection do not have category in the beginning of the rules, which make it hard to have an overview in daily modeller life.

**Comment by otykier** [comment]
As mentioned offline, we prefer not to change the names of existing rules in this collection. Going forward, we recommend using Microsoft's rules. If you are missing some rules from this collection in Microsoft's collection, please request them [here](https://github.com/microsoft/Analysis-Services/issues).
