### ISSUE TITLE
[Rule Submit] PERF: Key columns should be used in Relationships

### ISSUE THREAD

**Issue by Gezahegne** [TabularEditor/BestPracticeRules#7]
"ID": "PERF:_USED_IN_RELATIONSHIPS",
    "Name": "PERF: Key columns should be used in Relationships",
    "Category": null,
    "Description": "Don't include key columns that are not used for creating relationships unless they have special use.",
    "Severity": 3,
    "Scope": "DataColumn",
    "ScopeString": "Data Columns",
    "Expression": "((Name.ToLower().EndsWith(\"id\") or Name.ToLower().EndsWith(\"key\")))\nand (not UsedInRelationships.Any())",
    "FixExpression": null,
    "Compatibility": null,
    "IsValid": false

**Comment by otykier** [comment]
Won't add this, as this relies on specific naming conventions that could differ across organisations (use of "id" or "key" within column names)
