### ISSUE TITLE
[Rule Submit] META: Measure names should not have '_' '/' '\\'

### ISSUE THREAD

**Issue by Gezahegne** [TabularEditor/BestPracticeRules#8]
"ID": "META:_MEASURE_NAMES_SHOULDN'T_HAVE_'_'_'/'_'\\'",
    "Name": "META: Measure names should not have '_' '/' '\\'",
    "Category": null,
    "Description": "META: Measure names should not have '_' '/' '\\'",
    "Severity": 2,
    "Scope": "Measure",
    "ScopeString": "Measures",
    "Expression": "Name.Contains(\"_\") or Name.Contains(\"\\\") or Name.Contains(\"/\") and not IsHidden",
    "FixExpression": null,
    "Compatibility": null,
    "IsValid": false

**Comment by otykier** [comment]
Won't add, as this is organization-specific naming convention.
