### ISSUE TITLE
[Rule Submit] META: Match Partition Name & Table Name

### ISSUE THREAD

**Issue by Gezahegne** [TabularEditor/BestPracticeRules#9]
"ID": "META:_PARTITION_NAME_SHOULD_MATCHE_TABLE_NAME",
    "Name": "META: Match Partition Name & Table Name",
    "Category": null,
    "Description": "Partition Name should match Table Name.",
    "Severity": 10,
    "Scope": "Partition",
    "ScopeString": "Partitions",
    "Expression": "!Name.Equals(Table.Name) and Table.Partitions.Count()==1",
    "FixExpression": null,
    "Compatibility": null,
    "IsValid": false

**Comment by otykier** [comment]
Fixed, thanks for submitting.
